# Grammar is composed of definitions (named literals and named terminals) and some directives (at the end)
?start: statement+ // a program is composed of one or more statement

?statement: print_statement
            | input_statement
            | variable_declaration
            | variable_assignment
            | expression ";"?
            | if_statement
            | while_statement
            | return_statement
            | function_declaration
            | function_call ";"?
            | block

?block: "{" statement* "}"

?print_statement: "console" "." "log" "(" expression ")" ";"?

?input_statement: "prompt" "(" expression ")" ";"?

?variable_declaration :("let"|"var"|"const")? IDENTIFIER ("=" expression)?
?variable_assignment  : IDENTIFIER "=" expression

?function_declaration : "function" IDENTIFIER "(" parameter_list? ")" block

?parameter_list: IDENTIFIER ("," IDENTIFIER)*

?function_call: IDENTIFIER "(" argument_list? ")"

?argument_list: (IDENTIFIER "=")? expression ("," (IDENTIFIER "=")? expression)*

?if_statement : "if" "(" expression ")" statement ("else" statement)?  # this way we include all the possible cases, statement cn be a block or another if statement

?while_statement  : "while" "(" expression ")" statement

?expression: IDENTIFIER
            | NUMBER
            | STRING
            | "true" -> true
            | "false" -> false
            | "null" -> null
            | "undefined" -> undefined
            | logical_or
            | logical_and
            | equality  # equality with == in JS
            | strict_equality  # equality with === in JS
            | relational
            | additive
            | multiplicative
            | unary

?array  : "[" [expression ("," expression)*] "]"  # TODO come valutare espressioni in place

?logical_or: expression "||" expression

?logical_and: expression "&&" expression

?equality: expression "==" expression  # TODO verifica se serve rinominare per far funzionare
            | expression "!=" expression -> inequality

?strict_equality: expression "===" expression
                    | expression "!==" expression -> strict_inequality

?relational: expression "<" expression -> less_than
            | expression ">" expression -> greater_than
            | expression "<=" expression -> less_than_or_equal
            | expression ">=" expression -> greater_than_or_equal

?additive: expression "+" expression -> add  # TODO capisci come gestire precedenze e associatività (anche da slides)
            | expression "-" expression -> sub

?multiplicative: expression "*" expression -> mul
                | expression "/" expression -> div

?unary: "-" expression -> neg  #TODO controlla come gestire - e a cosa applicarlo
        | "!" expression -> not_

#TODO capisci come realizzare in termini di concateazione

STRING: "'" _STRING_INNER* "'"
        | '"' _STRING_INNER* '"'
        | "`" _STRING_INNER* "`"  # TODO nel backtick la valutaxione dei valori (come la f in python)



// comment management (ignore them)
COMMENT: "//" /[^\n]/* | "/*" /./* "*/"

%import common._STRING_INNER
%import common.CNAME -> IDENTIFIER
%import common.NUMBER
%import common.WS

%ignore COMMENT
%ignore WS

